### ISSUE TITLE
建议加上通过bookid下载书籍的功能，有些书在这个软件上的搜索引擎无法查询，然后就没办法下载

### ISSUE THREAD

**Issue by liangzhaoyuan12** [gyc123456-1/FanQieNovelSpider#1]
![图片](https://github.com/user-attachments/assets/9bd7ff81-26cc-46ba-8ac7-b56d96507c36)

**Comment by gyc123456-1** [comment]
很抱歉现在才看到你的issue，现已被采纳，将于下个版本一起加入
